"""
User registration/authentication service (passwords hashed with scrypt).
"""
from __future__ import annotations

import os
from datetime import datetime
from hashlib import scrypt
from secrets import compare_digest, token_bytes
from typing import Any, Dict, List, Optional

from pymongo.collection import Collection

from app.database import get_database

COLLECTION_NAME = "usuarios"
PASSWORD_KEY_LENGTH = 64
ALLOWED_ROLES = {"admin", "user"}
MIN_PASSWORD_LENGTH = 8


def _collection() -> Collection:
    return get_database()[COLLECTION_NAME]


def _map_user(doc: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "_id": str(doc["_id"]),
        "email": doc["email"],
        "name": doc.get("name"),
        "role": doc["role"],
        "createdAt": doc["createdAt"].isoformat() if doc.get("createdAt") else None,
        "updatedAt": doc["updatedAt"].isoformat() if doc.get("updatedAt") else None,
    }


def _normalize_email(email: str) -> str:
    return email.strip().lower()


def _ensure_role(role: Optional[str]) -> str:
    if not role:
        return "user"
    normalized = role.strip().lower()
    if normalized in ALLOWED_ROLES:
        return normalized
    raise ValueError(f"Rol no válido. Roles permitidos: {', '.join(ALLOWED_ROLES)}.")


def _ensure_password(password: Optional[str]) -> str:
    if not password or len(password) < MIN_PASSWORD_LENGTH:
        raise ValueError(f"La contraseña debe tener al menos {MIN_PASSWORD_LENGTH} caracteres.")
    return password


def _hash_password(password: str) -> str:
    salt = token_bytes(16)
    derived = scrypt(
        password.encode("utf-8"),
        salt=salt,
        n=2**14,
        r=8,
        p=1,
        dklen=PASSWORD_KEY_LENGTH,
    )
    return f"{salt.hex()}:{derived.hex()}"


def _verify_password(password: str, stored_hash: str) -> bool:
    try:
        salt_hex, hash_hex = stored_hash.split(":")
    except ValueError:
        return False
    salt = bytes.fromhex(salt_hex)
    stored = bytes.fromhex(hash_hex)
    derived = scrypt(
        password.encode("utf-8"),
        salt=salt,
        n=2**14,
        r=8,
        p=1,
        dklen=len(stored),
    )
    return compare_digest(stored, derived)


def register_user(payload: Dict[str, Any]) -> Dict[str, Any]:
    if not payload.get("email"):
        raise ValueError("El correo es obligatorio.")
    
    invitation_code = payload.get("invitationCode")
    if not invitation_code:
        raise ValueError("El código de invitación es obligatorio.")
        
    # Validate code and get role
    from app.services.invitation_service import validate_invitation_code, mark_invitation_code_as_used
    role = validate_invitation_code(invitation_code)

    email = _normalize_email(payload["email"])
    password = _ensure_password(payload.get("password"))
    # role is now determined by the invitation code

    if _collection().find_one({"email": email}):
        raise ValueError("Ya existe un usuario con ese correo.")

    now = datetime.utcnow()
    document = {
        "email": email,
        "name": payload.get("name") or None,
        "role": role,
        "passwordHash": _hash_password(password),
        "createdAt": now,
        "updatedAt": now,
    }
    result = _collection().insert_one(document)
    user_id = result.inserted_id
    document["_id"] = user_id
    
    # Mark code as used
    try:
        mark_invitation_code_as_used(invitation_code, str(user_id))
    except Exception as e:
        print(f"Error marking invitation code as used: {e}")
        
    return _map_user(document)


def authenticate_user(payload: Dict[str, Any]) -> Dict[str, Any]:
    if not payload.get("email") or not payload.get("password"):
        raise ValueError("Correo y contraseña son obligatorios.")
    email = _normalize_email(payload["email"])
    user = _collection().find_one({"email": email})
    if not user or not _verify_password(payload["password"], user["passwordHash"]):
        raise ValueError("Credenciales inválidas.")
    return _map_user(user)


INVITATION_REQUIRED_MARKER = "INVITATION_CODE_REQUIRED"


def authenticate_or_provision_ldap(payload: Dict[str, Any]) -> Dict[str, Any]:
    """
    Authenticate against LDAP and return the matching MongoDB user.

    SECURITY: Every account — 'user' or 'admin' — must be provisioned via an
    invitation code generated by an administrator. LDAP is one of two valid
    bootstrap paths (the other is email+password registration). On the first
    LDAP login, the caller must also supply a valid invitationCode; this single
    call validates the LDAP credentials, consumes the code, and creates the
    account with the role encoded in the code. Subsequent logins from the same
    LDAP account do not need the code.
    """
    from app.services.ldap_service import authenticate_ldap
    from app.services.invitation_service import (
        validate_invitation_code,
        mark_invitation_code_as_used,
    )

    if not payload.get("email") or not payload.get("password"):
        raise ValueError("Correo y contraseña son obligatorios.")

    ldap_info = authenticate_ldap(payload["email"], payload["password"])
    email = _normalize_email(ldap_info["email"])

    existing = _collection().find_one({"email": email})
    if existing:
        _collection().update_one(
            {"_id": existing["_id"]},
            {"$set": {"updatedAt": datetime.utcnow(), "lastLdapLoginAt": datetime.utcnow()}},
        )
        return _map_user(existing)

    # First-time LDAP login: requires invitation code to provision the account.
    invitation_code = (payload.get("invitationCode") or "").strip()
    if not invitation_code:
        raise ValueError(INVITATION_REQUIRED_MARKER)

    role = validate_invitation_code(invitation_code)

    now = datetime.utcnow()
    document = {
        "email": email,
        "name": ldap_info.get("name") or None,
        "role": role,
        "authProvider": "ldap",
        "createdAt": now,
        "updatedAt": now,
        "lastLdapLoginAt": now,
    }
    result = _collection().insert_one(document)
    user_id = result.inserted_id
    document["_id"] = user_id

    try:
        mark_invitation_code_as_used(invitation_code, str(user_id))
    except Exception as exc:
        print(f"Error marking invitation code as used: {exc}")

    return _map_user(document)


def change_password(email: str, current_password: str, new_password: str) -> bool:
    """
    Change the password of the authenticated user (identified by the JWT email).
    LDAP-provisioned accounts have no local password and must change it in LDAP.
    """
    if not current_password or not new_password:
        raise ValueError("La contraseña actual y la nueva son obligatorias.")
    user = _collection().find_one({"email": _normalize_email(email)})
    if not user:
        raise ValueError("Usuario no encontrado.")
    if not user.get("passwordHash"):
        raise ValueError("Esta cuenta usa LDAP; la contraseña se gestiona en el directorio institucional.")
    if not _verify_password(current_password, user["passwordHash"]):
        raise ValueError("La contraseña actual no es correcta.")
    _ensure_password(new_password)
    _collection().update_one(
        {"_id": user["_id"]},
        {"$set": {"passwordHash": _hash_password(new_password), "updatedAt": datetime.utcnow()}},
    )
    return True


def list_users() -> List[Dict[str, Any]]:
    cursor = _collection().find().sort("createdAt", -1)
    return [_map_user(doc) for doc in cursor]


def is_admin(email: str) -> bool:
    user = _collection().find_one({"email": _normalize_email(email)})
    return user is not None and user.get("role") == "admin"
